### ISSUE TITLE
Write-Up / Documentation Deliverable

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2021#35]
Week 3/26/21

To-Do;

1. Outline
2. Business problem
3. Data Description
4. Data Cleaning

Data Cleaning
1. Temprature Imputation
2. Project Removal
3. Tootsie Rools
4. Outlier Removal based on Price.

**Comment by kelsey-codes** [comment]
see draft here: https://docs.google.com/document/d/1_vi8GoHXBjOrom-mqLp6R-lSfh4ppT9-vErI50BL5Fk/edit#
