### ISSUE TITLE
Slide Deck

### ISSUE THREAD

**Issue by sammer21** [Kydoimos97/CapstoneMSBA2021#41]
Build out slide deck framework for presentation. Sam to work on this. Add in visualizations when team meets 4/15/2021

- Download template 
- Follow guidelines from Jeff
- Visualizations to be added in once analysis is complete -- ETA 4/14/2021

**Comment by kelsey-codes** [comment]
Draft started in the google drive: https://docs.google.com/presentation/u/1/d/1d7LA2--ZNnzXqZuyVC_YxIh-SCse4EGrsZ0DMn0drJc/edit?usp=drive_web&ouid=101233882473378624315

**Comment by sammer21** [comment]
Hey everyone. I have done a framework for the final presentation. Tomorrow we can work on filling it in with the appropriate visualizations and information and/or change if needed. Here is the link:

https://docs.google.com/presentation/d/14LRl5RMmComINgAykRfuWrCsGvol400_d5ghfX4zpyg/edit?usp=sharing

**Comment by Kydoimos97** [comment]
[https://docs.google.com/presentation/d/1-W8KjcDDbRyRJkqF8mEWEuchSEvjHVho7LuT7S1jGeQ/edit?usp=sharing](https://docs.google.com/presentation/d/1-W8KjcDDbRyRJkqF8mEWEuchSEvjHVho7LuT7S1jGeQ/edit?usp=sharing)

**Comment by timgain** [comment]
I know some changes were being made to the slide deck.  Are we able to load that revised version to the shared Google Drive folder?  Just looking to include some of the revised images in the report.

**Comment by Kydoimos97** [comment]
[Maverik Final Presentation.pptx](https://github.com/Kydoimos97/CapstoneMSBA2020/files/6332424/Maverik.Final.Presentation.pptx)

Here is the PPT file, this is better then the google slides version because google slides compresses images.

**Comment by Kydoimos97** [comment]
### New Powerpoint Layout

1. Presented Problem from Maverick [Business Problem | Data | Objective]
2. Design Scope and Decisions [Granularity | Computational Limitations]
3. Introduce Solution [Applet | Design]
4. How and why does the solution work [Seaonsality | Arima]
5. How well does the solution work [Global performance metrics | Error Messages]
